# Engineering DTBs (agassi) - only these are built, all upstream/original
# board dtbs have been removed from the build to avoid conflicts.
dtb-y := \
	Qualcomm_Technologies,_Inc._APQ8017-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._APQ8017-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8017-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._APQ8017-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8053_CDP.dtb \
	Qualcomm_Technologies,_Inc._APQ8053_External_Codec_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8053_IOT_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8053_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8937-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._APQ8937-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._APQ8937-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._APQ8937-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8937_QGP_TMO.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8937_QRD_SKU5.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8937_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917-PMI8950_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8917_External_Audio_Codec_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8917_RUMI.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8937_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8940_QRD_SKU7.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8920-PMI8950_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8937_QRD_SKU2.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8937_QRD_SKU2_DVT1.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8937_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8950_QRD_SKU1.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8950_QRD_SKU1_DVT1.dtb \
	Qualcomm_Technologies,_Inc._MSM8937-PMI8950_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8937_External_Audio_Codec_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8937_RUMI.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8937_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8937_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8937_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8940_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8940_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8940_QRD_SKU7.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8940_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8950_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8950_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8950_QRD_SKU6.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8950_QRD_SKU7.dtb \
	Qualcomm_Technologies,_Inc._MSM8940-PMI8950_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8940_External_Audio_Codec_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8952_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM8952_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8952_QRD_SKUM.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_CDP_04.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_CDP_29.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_External_Codec_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_External_Codec_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_IOT_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_MTP.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_QRD_SKU3.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_RCM.dtb \
	Qualcomm_Technologies,_Inc._MSM8953_RUMI.dtb \
	Qualcomm_Technologies,_Inc._MSMTitaninum_Simulator.dtb \
	Qualcomm_Technologies,_Inc._MSM_8952_External_Audio_Codec_CDP.dtb \
	Qualcomm_Technologies,_Inc._MSM_COBALT_RUMI.dtb \
	Qualcomm_Technologies,_Inc._MSM_COBALT_SIM.dtb \
	Qualcomm_Technologies,_Inc._MSM_COBALT_V2_RUMI.dtb \
	Qualcomm_Technologies,_Inc._MSM_COBALT_V2_SIM.dtb \
	Qualcomm_Technologies,_Inc._MSM_cobalt.dtb \
	Qualcomm_Technologies,_Inc._MSM_cobalt_v1.dtb \
	Qualcomm_Technologies,_Inc._MSM_cobalt_v2_20.dtb \
	Qualcomm_Technologies,_Inc._MSM_cobalt_v2_28.dtb

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
	$(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
